const CREATE_BOOK = 'CREATE_BOOK';
const REMOVE_BOOK = 'REMOVE_BOOK';
const CHANGE_FILTER = 'CHANGE_FILTER';
const UPDATE_BOOK_LIST = 'UPDATE_BOOK_LIST';


/* API Acitons */

const GET_BOOKLIST = 'GET_BOOKLIST';
const RECIEVED_DATA = 'RECIEVED_DATA';
const STORE_BOOK = 'STORE_BOOK';
const DELETE_BOOK = 'DELETE_BOOK'

const randomId = () => Math.floor(Math.random() * Math.floor(50000));

export {
  CREATE_BOOK, REMOVE_BOOK, CHANGE_FILTER,UPDATE_BOOK_LIST, randomId,
  GET_BOOKLIST, RECIEVED_DATA, STORE_BOOK, DELETE_BOOK
};
